#!/usr/bin/env python3
import sys
import analizador_lexico

def main():
    if len(sys.argv) < 2:
        print("Error. Uso correcto: ./analizador <archivo_de_prueba>");
        sys.exit(1);

    fileName = sys.argv[1];
    analizador_lexico.read_source(fileName);

if __name__ == "__main__":
    main()